# Generated by Django 3.1.1 on 2020-10-01 04:47

import Company_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_App', '0003_remove_employeesattendancecollection_break_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.CharField(max_length=30, null=True, validators=[Company_App.models.validate_email]),
        ),
    ]
