# Generated by Django 3.1.1 on 2020-10-01 06:00

import Company_App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_App', '0006_auto_20201001_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='phone_no',
            field=models.PositiveIntegerField(null=True, validators=[Company_App.models.validate_phone]),
        ),
    ]
